// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8ajHbKaokaYtBr5TDIqZpEUMgqxrAA8M',
    appId: '1:504550345970:web:49691949f413c142fe546b',
    messagingSenderId: '504550345970',
    projectId: 'flutterhackathonapp',
    authDomain: 'flutterhackathonapp.firebaseapp.com',
    storageBucket: 'flutterhackathonapp.appspot.com',
    measurementId: 'G-NMEYS1LJF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCorK0Yo4ObxvWkiKqWJBYfWtymKPJy8uM',
    appId: '1:504550345970:android:39a085dc4b2016eefe546b',
    messagingSenderId: '504550345970',
    projectId: 'flutterhackathonapp',
    storageBucket: 'flutterhackathonapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW0x3zwOAqRDj0USrQLnIfBu__BRICfq4',
    appId: '1:504550345970:ios:7323a67ccd843dd1fe546b',
    messagingSenderId: '504550345970',
    projectId: 'flutterhackathonapp',
    storageBucket: 'flutterhackathonapp.appspot.com',
    iosClientId: '504550345970-ojjf9ha3s1o1fkehkvd01ikb47opv4d4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterhackathonapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW0x3zwOAqRDj0USrQLnIfBu__BRICfq4',
    appId: '1:504550345970:ios:7323a67ccd843dd1fe546b',
    messagingSenderId: '504550345970',
    projectId: 'flutterhackathonapp',
    storageBucket: 'flutterhackathonapp.appspot.com',
    iosClientId: '504550345970-ojjf9ha3s1o1fkehkvd01ikb47opv4d4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterhackathonapp',
  );
}
